version: 2.1

orbs:
    unity: game-ci/unity@1.3.0

workflows:
    build:
        jobs:
            - checkout
            - unity/build:
                executor:
                    name: "unity/windows-2022"
                    target_platform: "windows-il2cpp"
                    editor_version: "2021.3.13f1"
                name: "Build-windowsx64-il2cpp"
                build-name: ""
                project-path: .
                build-target: StandaloneWindows64
                compress: true
                custom-parameters: ""
                store-artifacts: true